In [49]:
import pandas as pd

In [50]:
data = pd.read_csv('/Users/macbookpro/Downloads/Churn_Modelling.csv')

In [51]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


I don't think i'll have need for 3 columns
i -- RowNumber
ii -- CustomerId
iii -- Surname

So i can decide to drop them


In [53]:
# drop the irrelevant features in the dataset
data.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1, inplace=True)

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [55]:
data.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [56]:
# what is the  distribution of the countries present in our data
data.Geography.value_counts() 

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [57]:
data['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [58]:
# let's check for the Gender class distribution
data.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

Part of the data pre-processing task we might need to do is to categorically encode the categorical variables. 
1. Geography
2. Gender
3. Exited --  This is initially formatted as an int64 but it's showing a class which we need to format it correctly.
4. HasCrCard
5. IsActiveMember

In [59]:
data.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [60]:
# Split the variables into features and labels
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [61]:
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [62]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [63]:
print(X)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [65]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [66]:
#data['HasCrCard'] = le.transform(data['HasCrCard'])
#data['IsActiveMember'] = le.transform(data['IsActiveMember'])

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, [3,-1]] = sc.fit_transform(X_train[:, [3,-1]])
X_test[:, [3,-1]] = sc.transform(X_test[:, [3,-1]])

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_auc_score

In [70]:
# define a function to train and assess the model
def model_assesor(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    cm = confusion_matrix(y_test, y_pred)
    print("roc_auc_score {0:.4f}\n".format(roc_auc_score(y_test, y_pred)))
    print("accuracy_score {0:.4f}\n".format(accuracy_score(y_test, y_pred)))
    print("classification Report: \n{}\n".format(classification_report(y_test, y_pred)))
    print("Confusion Matrix: \n{}\n".format(cm))
    

In [71]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
model_assesor(classifier, X_train, X_test, y_train, y_test)

roc_auc_score 0.5000

accuracy_score 0.7925

classification Report: 
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1585
           1       0.00      0.00      0.00       415

    accuracy                           0.79      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.63      0.79      0.70      2000


Confusion Matrix: 
[[1585    0]
 [ 415    0]]



/Users/macbookpro/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/macbookpro/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/macbookpro/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### K NN Algorithm

In [72]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_assesor(classifier_knn, X_train, X_test, y_train, y_test)

roc_auc_score 0.5112

accuracy_score 0.7525

classification Report: 
              precision    recall  f1-score   support

           0       0.80      0.92      0.86      1585
           1       0.25      0.10      0.14       415

    accuracy                           0.75      2000
   macro avg       0.52      0.51      0.50      2000
weighted avg       0.68      0.75      0.71      2000


Confusion Matrix: 
[[1464  121]
 [ 374   41]]



### SVM Classifier

In [73]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'linear', random_state = 0)
model_assesor(classifier_svm, X_train, X_test, y_train, y_test)

roc_auc_score 0.5285

accuracy_score 0.7785

classification Report: 
              precision    recall  f1-score   support

           0       0.80      0.96      0.87      1585
           1       0.38      0.10      0.16       415

    accuracy                           0.78      2000
   macro avg       0.59      0.53      0.52      2000
weighted avg       0.71      0.78      0.72      2000


Confusion Matrix: 
[[1515   70]
 [ 373   42]]



### Naive's Bayes Theorem

In [74]:
from sklearn.naive_bayes import GaussianNB
classifier_bayes = GaussianNB()
model_assesor(classifier_bayes, X_train, X_test, y_train, y_test)


roc_auc_score 0.5195

accuracy_score 0.7825

classification Report: 
              precision    recall  f1-score   support

           0       0.80      0.97      0.88      1585
           1       0.37      0.07      0.12       415

    accuracy                           0.78      2000
   macro avg       0.59      0.52      0.50      2000
weighted avg       0.71      0.78      0.72      2000


Confusion Matrix: 
[[1536   49]
 [ 386   29]]



### Decision Tree Classifier

In [75]:
from sklearn.tree import DecisionTreeClassifier
classifier_dclf = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
model_assesor(classifier_dclf, X_train, X_test, y_train, y_test)

roc_auc_score 0.6873

accuracy_score 0.7905

classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.86      0.87      1585
           1       0.50      0.51      0.50       415

    accuracy                           0.79      2000
   macro avg       0.68      0.69      0.69      2000
weighted avg       0.79      0.79      0.79      2000


Confusion Matrix: 
[[1369  216]
 [ 203  212]]



### Random Forest Classifier

In [76]:
from sklearn.ensemble import RandomForestClassifier
classifier_rfclf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
model_assesor(classifier_rfclf, X_train, X_test, y_train, y_test)

roc_auc_score 0.6971

accuracy_score 0.8525

classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1585
           1       0.75      0.43      0.55       415

    accuracy                           0.85      2000
   macro avg       0.81      0.70      0.73      2000
weighted avg       0.84      0.85      0.84      2000


Confusion Matrix: 
[[1526   59]
 [ 236  179]]



### Bagging

In [77]:
from sklearn.ensemble import BaggingClassifier

In [78]:
# bagging classifier with the decision tree model as the base estimator
bag_clf = BaggingClassifier(estimator=classifier_dclf, n_estimators=5000, bootstrap=True, n_jobs=-1, random_state=42)

In [79]:
model_assesor(bag_clf, X_train, X_test, y_train, y_test)

roc_auc_score 0.7226

accuracy_score 0.8620

classification Report: 
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1585
           1       0.76      0.48      0.59       415

    accuracy                           0.86      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000


Confusion Matrix: 
[[1523   62]
 [ 214  201]]



### Adaboost

In [80]:
from sklearn.ensemble import AdaBoostClassifier

In [81]:
ada_clf = AdaBoostClassifier()

In [82]:
model_assesor(ada_clf, X_train, X_test, y_train, y_test)

roc_auc_score 0.7142

accuracy_score 0.8585

classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1585
           1       0.76      0.47      0.58       415

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.85      0.86      0.85      2000


Confusion Matrix: 
[[1523   62]
 [ 221  194]]



### Cross Validation

In [83]:
from sklearn.model_selection import cross_val_score
cross_val_score(ada_clf,X, y, cv=5)

array([0.857 , 0.865 , 0.8545, 0.8615, 0.852 ])

### Gradient Boosting


In [84]:
from sklearn.ensemble import GradientBoostingClassifier

In [85]:
gb_clf = GradientBoostingClassifier()

In [86]:
model_assesor(gb_clf, X_train, X_test, y_train, y_test)

roc_auc_score 0.7151

accuracy_score 0.8600

classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.96      0.92      1585
           1       0.77      0.47      0.58       415

    accuracy                           0.86      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000


Confusion Matrix: 
[[1526   59]
 [ 221  194]]



One of the obvious reasons i am having a problem of identifying one class better than the other is because of the imbalance that is present in our data. To solve this problem, we can take 3 different approaches.

1. Undersampling
2. Oversampling
3. SMOTE.

This resampling will help balance the distributions of the classes present. I propose to go with the Oversampling because i'll have more data to train

### Oversampling

In [87]:
class_0, class_1 = data.Exited.value_counts()
# filter and split
data_class_0 = data[data['Exited']== 0]
data_class_1 = data[data['Exited']== 1]

In [88]:
data_class_1 = data_class_1.sample(class_0, replace=True)
final_df = pd.concat([data_class_0, data_class_1], axis=0)


CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
558          France     Female  41   6       0.00       1              1          1               143585.29        1         12
607          Spain      Female  33   2       108431.87  2              0          1               109291.39        1         11
606          France     Female  39   3       0.00       2              1          0               50560.45         1         11
555          Germany    Male    62   4       119817.33  1              0          1               43507.10         1         11
628          Germany    Female  51   10      115280.49  2              0          0               12628.61         1         11
                                                                                                                             ..
618          France     Male    37   2       168178.21  2              0          1               101273.23   

In [89]:
final_df['Exited'].value_counts()

Exited
0    7963
1    7963
Name: count, dtype: int64

In [95]:

X = final_df.drop(['Exited'], axis=1)
y = final_df['Exited']
# let's do some encoding now
X = np.array(ct.transform(X)) # ct is the column transformer object
y = le.transform(y) # le is the label encoder object

# let's split it again into the train test split for training our model
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

# let me standardize the numerical variables
X_train[:, [3,-1]] = sc.fit_transform(X_train[:, [3,-1]])
X_test[:, [3,-1]] = sc.transform(X_test[:, [3,-1]])

In [96]:
model_assesor(ada_clf, X_train, X_test, y_train, y_test)

roc_auc_score 0.7706

accuracy_score 0.7709

classification Report: 
              precision    recall  f1-score   support

           0       0.76      0.80      0.78      1605
           1       0.79      0.74      0.76      1581

    accuracy                           0.77      3186
   macro avg       0.77      0.77      0.77      3186
weighted avg       0.77      0.77      0.77      3186


Confusion Matrix: 
[[1286  319]
 [ 411 1170]]

